version: '3.8'

services:
  mysql:
    container_name: testauth-mysql
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOTPASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASENAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: ["--max_allowed_packet=512505856", "--sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"]
    restart: unless-stopped